=== xpinus/xrepo/apps/news-spider-cave/client/schema/spider.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/person.schema.json",
  "title": "Spider",
  "description": "A news spider object",
  "type": "object",
  "required": ["website", "name", "routes"],
  "properties": {
    "website": {
      "type": "string",
      "description": "The spider's target website"
    },
    "name": {
      "type": "string",
      "description": "The target's name"
    },
    "zhName": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "description": "The target website's language"
    },
    "country": {
      "type": "string",
      "description": "The target website's country"
    },
    "routes": {
      "type": "array",
      "description": "The target website's routes for crawling",
      "items": {
        "type": "object",
        "required": ["path", "selectors"],
        "properties": {
          "path": {
            "type": "string",
            "description": "The route's path"
          },
          "selectors": {
            "type": "array",
            "description": "The story's selectors",
            "items": {
              "type": "object",
              "required": ["label", "selector", "fields"],
              "properties": {
                "label": {
                  "type": "array",
                  "description": "The story's label",
                  "items": {
                    "type": "string"
                  }
                },
                "selector": {
                  "type": "string",
                  "description": "The story's selector"
                },
                "fields": {
                  "type": "array",
                  "description": "The story's fields",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "The field's name",
                        "minLength": 1,
                        "maxLength": 20
                      },
                      "selector": {
                        "type": "string",
                        "description": "The field's selector"
                      },
                      "type": {
                        "type": "string",
                        "description": "The field's type"
                      }
                    },
                    "required": ["name", "selector", "type"]
                  }
                },
                "limit": {
                  "type": "integer",
                  "description": "The crawled stories count limit",
                  "minimum": 1
                }
              }
            }
          }
        }
      }
    }
  }
}

=== xpinus/xrepo/apps/news-spider-cave/client/cave/guancha.json
{
  "$schema": "http://127.0.0.1:9001/schema/spider.schema.json",
  "website": "https://www.guancha.cn/",
  "name": "guancha",
  "zhName": "观察者网",
  "language": "zh-CN",
  "country": "CN",
  "routes": [
    {
      "path": "/internation",
      "selectors": [
        {
          "label": ["国际"],
          "selector": ".new-header-list h4 a",
          "fields": [
            {
              "name": "title",
              "selector": "",
              "type": "string"
            }
          ],
          "limit": 3
        }
      ]
    }
  ]


}
